<a href="https://colab.research.google.com/github/ishikabalodhi/Isha-pythoncodes-/blob/main/9april.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!pip install numpy
!pip install pandas
import numpy as np
import pandas as nd
l1=[1,2,3,4,5]
t1=(7,8,9,99)
a1=np.array(l1)
np.array(l1)


array([1, 2, 3, 4, 5])

In [5]:
l2=[0,0,0,0,0]
a3=np.array([l1,l2])
print(a3)

[[1 2 3 4 5]
 [0 0 0 0 0]]


In [6]:
a4=np.arange(0,20).reshape(4,5)
print(a4)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [7]:
a4=np.arange(0,20,2).reshape(2,5)
print(a4)

[[ 0  2  4  6  8]
 [10 12 14 16 18]]


In [9]:
a5=np.random.randint(0,100,20)
print(a5)

[85 30 77 26 31 47 88 30 67 20 17 65 38 33 84 24 32  0 83 46]


In [10]:
a6=np.arange(0,100).reshape(10,10)
print(a6)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [11]:
a6[5:6 ,3:8]


array([[53, 54, 55, 56, 57]])

In [12]:
a6[9: ,9:]

array([[99]])

In [10]:
l1=[1,2,3,4,5]
t1=(1,2,3,4,5)
a4=np.arange(0,20).reshape(4,5)
print(a4)
a5=np.random.randint(0,100,20).reshape(4,5)
print(a5)
a5*=2

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[37 70 30 83 44]
 [ 0 43 72 88 99]
 [ 9 13  6 60 67]
 [ 4 20 51 63 62]]
